### PR TITLE
Providing token

### PR DESCRIPTION
**Pull request by MichaelBorde**
When HIS connectivity is toggled on via EOVE-150 user interface, server will generate a **new and unique** communication token.
This token will not be required before a configured delay (typically 5 min).
During such delay client can connect, start high level communication and read the token in a response message.
Client should store this token (in a persistent storage) to be able to connect to the server later.
When the delay is expired the server will require the token for subsequent connections.
Note that client stays connected when server starts requiring token, there is no need to reconnect yet.

Example of communication start from client:

```json
{
  "type": "START_COMMUNICATION",
  "payload": {
    "token": "eoh_6af83e7c494e47d29c3ddc80ac0df354"
  }
}
```

Example of succeeded response from server when token is not required yet:

```json
{
  "type": "START_COMMUNICATION_SUCCEEDED",
  "payload": {
    "apiVersion": "1.0.0",
    "token": "eoh_6af83e7c494e47d29c3ddc80ac0df354"
  }
}
```

Example of error message client might receive:

```json
{
  "type": "START_COMMUNICATION_FAILED",
  "payload": {
    "reason": "missingToken"
  }
}
```

### CODE REVIEW

**Review by pierreroth64 — CHANGES_REQUESTED** [review]
Would it be possible to add an environment var to force usage of a given token ? Useful for testing 🙏 

Using this patch...
```javascript
private readTokenIfAny(): Promise<string | undefined> {
    return process.env.HIS_TOKEN
      ? Promise.resolve(process.env.HIS_TOKEN)
      : readFile(this.tokenFile, { encoding: 'utf-8' }).catch((error) => {
          if (error.code !== 'ENOENT') {
            this.logger.error('Unexpected error while reading token', error);
            this.emit(ClientEventType.error, error);
          }
          return undefined;
        });
  }
```
... I can see that starting communication is impossible 👍 

Capture d’écran 2022-04-25 à 11 58 04

**Comment by MichaelBorde** [comment]
What about writing the token you want to the token file and then launch the
script ?

**Comment by pierreroth64** [comment]
> What about writing the token you want to the token file and then launch the script ?

Yes, this is a solution but the path the file where the token is stored is not displayed. We could add a console.log such as `reading token from /path/to/token-file` to help the tester.

**Comment by MichaelBorde** [comment]
I think a debug log is fine.

**Comment by dfelipe64** [comment]
Test are done and PASS. Please, clarify if requested changes must be done or not before merging

**Comment by MichaelBorde** [comment]
> Test are done and PASS. Please, clarify if requested changes must be done or not before merging

Everything seems ok with this commit: https://github.com/eove/his-api/pull/8/commits/f43a39a1d06210f773acc2f079c11fc2a30a4c72

**Pull request merged**
